//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrinityCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrinityCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ARIALN {
            get {
                object obj = ResourceManager.GetObject("ARIALN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bluesocket {
            get {
                object obj = ResourceManager.GetObject("bluesocket", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;KeyValues&gt;
        ///    &lt;AI&gt;
        ///        &lt;Item Id=&quot;0&quot; Description=&quot;NullAI&quot; /&gt;
        ///        &lt;Item Id=&quot;1&quot; Description=&quot;AggressorAI&quot; /&gt;
        ///        &lt;Item Id=&quot;2&quot; Description=&quot;ReactorAI&quot; /&gt;
        ///        &lt;Item Id=&quot;3&quot; Description=&quot;GuardAI&quot; /&gt;
        ///        &lt;Item Id=&quot;4&quot; Description=&quot;PetAI&quot; /&gt;
        ///        &lt;Item Id=&quot;5&quot; Description=&quot;TotemAI&quot; /&gt;
        ///        &lt;Item Id=&quot;6&quot; Description=&quot;EventAI&quot; /&gt;
        ///        &lt;Item Id=&quot;7&quot; Description=&quot;SmartAI&quot; /&gt;
        ///    &lt;/AI&gt;
        ///    &lt;CreatureRank&gt;
        ///        &lt;Item Id=&quot;0&quot; Description=&quot;Norma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cb_data {
            get {
                return ResourceManager.GetString("cb_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copper {
            get {
                object obj = ResourceManager.GetObject("copper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator			Nadromar
        ///
        ///External libraries by:
        ///DBC Viewer		tomrus88
        ///DBC &amp; maps extractor	cMangos
        ///Model Viewer		Wowhead
        ///Web browser		CefSharp.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DailyActiveQuestIcon {
            get {
                object obj = ResourceManager.GetObject("DailyActiveQuestIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DailyQuestIcon {
            get {
                object obj = ResourceManager.GetObject("DailyQuestIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- $Id: dbclayout.xml 2010-18-09 0:13:00 TOM_RUS $ --&gt;
        ///&lt;DBFilesClient&gt;
        ///  &lt;Achievement build=&quot;13117&quot;&gt;
        ///    &lt;index&gt;
        ///      &lt;primary&gt;id&lt;/primary&gt;
        ///    &lt;/index&gt;
        ///    &lt;field type=&quot;uint&quot; name=&quot;id&quot; /&gt;
        ///    &lt;field type=&quot;int&quot; name=&quot;factionFlag&quot; /&gt;
        ///    &lt;field type=&quot;int&quot; name=&quot;mapId&quot; /&gt;
        ///    &lt;field type=&quot;uint&quot; name=&quot;parentAchievement&quot; /&gt;
        ///    &lt;field type=&quot;string&quot; name=&quot;name&quot; /&gt;
        ///    &lt;field type=&quot;string&quot; name=&quot;description&quot; /&gt;
        ///    &lt;field type=&quot;uint&quot; name=&quot;categoryId&quot; /&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dbclayout {
            get {
                return ResourceManager.GetString("dbclayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRIZQT__ {
            get {
                object obj = ResourceManager.GetObject("FRIZQT__", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gold {
            get {
                object obj = ResourceManager.GetObject("gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IncompleteQuestIcon {
            get {
                object obj = ResourceManager.GetObject("IncompleteQuestIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap metasocket {
            get {
                object obj = ResourceManager.GetObject("metasocket", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MORPHEUS {
            get {
                object obj = ResourceManager.GetObject("MORPHEUS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap QuestGreeting {
            get {
                object obj = ResourceManager.GetObject("QuestGreeting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type $N to display a player&apos;s name or $C for a player&apos;s class in a quest.
        ///Leave the value at 0 if you don&apos;t want to use a feature.
        ///Use the lookup tool on the right to find ID&apos;s.
        ///Please report any bugs and suggestions on GitHub.
        ///Configure your database &amp; dbc in settings to use the lookup tool and other features.
        ///You need to restart TrinityCore and sometimes delete your WoW Cache to view your creations.
        ///Doubleclick a row in the Lookup Tool to view it&apos;s in-game model if possible.
        ///You can click-drag the  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RandomTips {
            get {
                return ResourceManager.GetString("RandomTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redsocket {
            get {
                object obj = ResourceManager.GetObject("redsocket", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap silver {
            get {
                object obj = ResourceManager.GetObject("silver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SKURRI {
            get {
                object obj = ResourceManager.GetObject("SKURRI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tclogo {
            get {
                object obj = ResourceManager.GetObject("tclogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yellowsocket {
            get {
                object obj = ResourceManager.GetObject("yellowsocket", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
